import { Project, TeamMember, HierarchyNode, MemberAssignment } from './types';

export const mockProject: Project = {
  id: 'proj-1',
  name: 'Digital Transformation Initiative',
  description: 'A comprehensive project to modernize our digital infrastructure and processes',
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
};

export const mockTeamMembers: TeamMember[] = [
  {
    id: 'tm-1',
    name: 'Sarah Johnson',
    email: 'sarah.j@company.com',
    photo_url: 'https://images.pexels.com/photos/3785079/pexels-photo-3785079.jpeg?auto=compress&cs=tinysrgb&w=400',
    role_type: 'Project Lead',
    bio: 'Experienced project leader with 10+ years in digital transformation',
    skills: ['Leadership', 'Strategy', 'Agile'],
    created_at: new Date().toISOString(),
  },
  {
    id: 'tm-2',
    name: 'Michael Chen',
    email: 'michael.c@company.com',
    photo_url: 'https://images.pexels.com/photos/2379004/pexels-photo-2379004.jpeg?auto=compress&cs=tinysrgb&w=400',
    role_type: 'Product Owner',
    bio: 'Product strategist focused on user-centered design',
    skills: ['Product Strategy', 'UX', 'Analytics'],
    created_at: new Date().toISOString(),
  },
  {
    id: 'tm-3',
    name: 'Emma Rodriguez',
    email: 'emma.r@company.com',
    photo_url: 'https://images.pexels.com/photos/3686769/pexels-photo-3686769.jpeg?auto=compress&cs=tinysrgb&w=400',
    role_type: 'Tech Lead',
    bio: 'Full-stack architect with cloud expertise',
    skills: ['Architecture', 'Cloud', 'DevOps'],
    created_at: new Date().toISOString(),
  },
  {
    id: 'tm-4',
    name: 'James Wilson',
    email: 'james.w@company.com',
    photo_url: 'https://images.pexels.com/photos/2182970/pexels-photo-2182970.jpeg?auto=compress&cs=tinysrgb&w=400',
    role_type: 'Senior Developer',
    bio: 'Backend specialist with microservices experience',
    skills: ['Node.js', 'Python', 'Kubernetes'],
    created_at: new Date().toISOString(),
  },
  {
    id: 'tm-5',
    name: 'Aisha Patel',
    email: 'aisha.p@company.com',
    photo_url: 'https://images.pexels.com/photos/3781338/pexels-photo-3781338.jpeg?auto=compress&cs=tinysrgb&w=400',
    role_type: 'Senior Developer',
    bio: 'Frontend expert passionate about accessibility',
    skills: ['React', 'TypeScript', 'Accessibility'],
    created_at: new Date().toISOString(),
  },
  {
    id: 'tm-6',
    name: 'David Kim',
    email: 'david.k@company.com',
    photo_url: 'https://images.pexels.com/photos/2379005/pexels-photo-2379005.jpeg?auto=compress&cs=tinysrgb&w=400',
    role_type: 'UX Designer',
    bio: 'Design thinker focused on elegant solutions',
    skills: ['UI/UX', 'Figma', 'User Research'],
    created_at: new Date().toISOString(),
  },
  {
    id: 'tm-7',
    name: 'Lisa Martinez',
    email: 'lisa.m@company.com',
    photo_url: 'https://images.pexels.com/photos/3756681/pexels-photo-3756681.jpeg?auto=compress&cs=tinysrgb&w=400',
    role_type: 'QA Lead',
    bio: 'Quality advocate with test automation expertise',
    skills: ['Test Automation', 'CI/CD', 'Quality Strategy'],
    created_at: new Date().toISOString(),
  },
  {
    id: 'tm-8',
    name: 'Tom Anderson',
    email: 'tom.a@company.com',
    photo_url: 'https://images.pexels.com/photos/2380794/pexels-photo-2380794.jpeg?auto=compress&cs=tinysrgb&w=400',
    role_type: 'DevOps Engineer',
    bio: 'Infrastructure specialist ensuring reliable deployments',
    skills: ['AWS', 'Docker', 'Terraform'],
    created_at: new Date().toISOString(),
  },
  {
    id: 'tm-9',
    name: 'Nina Foster',
    email: 'nina.f@company.com',
    photo_url: 'https://images.pexels.com/photos/3765035/pexels-photo-3765035.jpeg?auto=compress&cs=tinysrgb&w=400',
    role_type: 'Business Analyst',
    bio: 'Data-driven analyst bridging business and tech',
    skills: ['Analysis', 'SQL', 'Stakeholder Management'],
    created_at: new Date().toISOString(),
  },
  {
    id: 'tm-10',
    name: 'Carlos Rivera',
    email: 'carlos.r@company.com',
    photo_url: 'https://images.pexels.com/photos/2269872/pexels-photo-2269872.jpeg?auto=compress&cs=tinysrgb&w=400',
    role_type: 'Scrum Master',
    bio: 'Agile coach facilitating high-performing teams',
    skills: ['Scrum', 'Facilitation', 'Team Building'],
    created_at: new Date().toISOString(),
  },
];

export const mockHierarchyNodes: HierarchyNode[] = [
  {
    id: 'hn-1',
    project_id: 'proj-1',
    parent_id: null,
    role_title: 'Project Lead',
    role_description: 'Overall project leadership and strategic direction',
    position_x: 0,
    position_y: 0,
    level: 0,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'hn-2',
    project_id: 'proj-1',
    parent_id: 'hn-1',
    role_title: 'Product Owner',
    role_description: 'Product vision and backlog management',
    position_x: -200,
    position_y: 150,
    level: 1,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'hn-3',
    project_id: 'proj-1',
    parent_id: 'hn-1',
    role_title: 'Tech Lead',
    role_description: 'Technical architecture and team guidance',
    position_x: 200,
    position_y: 150,
    level: 1,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'hn-4',
    project_id: 'proj-1',
    parent_id: 'hn-2',
    role_title: 'UX Designer',
    role_description: 'User experience and interface design',
    position_x: -300,
    position_y: 300,
    level: 2,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'hn-5',
    project_id: 'proj-1',
    parent_id: 'hn-2',
    role_title: 'Business Analyst',
    role_description: 'Requirements analysis and stakeholder liaison',
    position_x: -100,
    position_y: 300,
    level: 2,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'hn-6',
    project_id: 'proj-1',
    parent_id: 'hn-3',
    role_title: 'Senior Developer',
    role_description: 'Backend development and API design',
    position_x: 100,
    position_y: 300,
    level: 2,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'hn-7',
    project_id: 'proj-1',
    parent_id: 'hn-3',
    role_title: 'Senior Developer',
    role_description: 'Frontend development and user interfaces',
    position_x: 300,
    position_y: 300,
    level: 2,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'hn-8',
    project_id: 'proj-1',
    parent_id: 'hn-1',
    role_title: 'Scrum Master',
    role_description: 'Agile facilitation and process improvement',
    position_x: 0,
    position_y: 150,
    level: 1,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const mockMemberAssignments: MemberAssignment[] = [
  {
    id: 'ma-1',
    hierarchy_node_id: 'hn-1',
    team_member_id: 'tm-1',
    assigned_at: new Date().toISOString(),
  },
  {
    id: 'ma-2',
    hierarchy_node_id: 'hn-2',
    team_member_id: 'tm-2',
    assigned_at: new Date().toISOString(),
  },
  {
    id: 'ma-3',
    hierarchy_node_id: 'hn-3',
    team_member_id: 'tm-3',
    assigned_at: new Date().toISOString(),
  },
];
